version: '3'

services:
  app:
    build: .
    image: php:8.0-apache
    container_name: php_app
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/html/src
      - ./php.ini-production:/usr/local/etc/php/php.ini-production
    depends_on:
      - db

  db:
    image: mariadb
    container_name: mariadb_db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: leave_system
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
volumes:
  db_data:
